services:
  backend:
    build: .
    ports:
      - "9999:9999"
      - "5005:5005"
    networks:
      - payment-processor
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

networks:
  payment-processor:
    external: true