services:
  backend:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  db:
    image: postgres
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
