x-api-templates:
  app: &api-template

    build: .
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    environment:
      JAVA_OPTS: >-
        -Xms50m
        -Xmx90m
        -Xscmx30m
        -Xshareclasses:cacheDir=/tmp
        -Xgc:concurrentScavenge
        -Xquickstart
        -Xtune:virtualized
        -XX:+UseContainerSupport
        -XX:+IdleTuningGcOnIdle
        -Xdisableexplicitgc
        -XX:+OptimizeStringConcat

    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: "160MB"

services:
  api-1:
    <<: *api-template
    container_name: api-1
    hostname: api-1

  api-2:
    <<: *api-template
    container_name: api-2
    hostname: api-2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"


  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "10MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
