x-api-templates:
  app: &api-template
    build: .
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    environment:
      JAVA_OPTS: >-
        -Xms24m -Xmx80m
        -XX:MaxMetaspaceSize=32m
        -Dio.netty.maxDirectMemory=8m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:G1HeapRegionSize=1m
        -XX:+UseStringDeduplication
        -XX:+AlwaysActAsServerClassMachine
        -Xlog:disable
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseZGC
#    deploy:
#      resources:
#        limits:
#          cpus: '0.55'
#          memory: "155MB"

services:
  api-1:
    <<: *api-template
    container_name: api-1
    hostname: api-1

  api-2:
    <<: *api-template
    container_name: api-2
    hostname: api-2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
#    deploy:
#      resources:
#        limits:
#          cpus: "0.2"
#          memory: "20MB"
    tmpfs:
      - /data

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - api-1
      - api-2
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: "20MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
